version: '3.4'

services:
  service1:
    image: service1
    build:
      context: .
      dockerfile: Service1/Dockerfile
    networks:
      - microservices
    ports:
      - "5001:5001"

  service2:
    image: service2
    build:
      context: .
      dockerfile: Service2/Dockerfile
    networks:
      - microservices
    ports:
      - "5002:5002"
    depends_on:
      - service1
    environment:
      - Service1Url=http://localhost:5001

  frontend:
    image: frontend
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    networks:
      - microservices
    ports:
      - "5000:5000"
    depends_on:
      - service2
    environment:
      - Service2Url=http://localhost:5002

networks:
  microservices:
    driver: bridge