version: '3.4'

services:
  service1:
    image: service1
    build:
      context: .
      dockerfile: Service1/Dockerfile
    networks:
      - microservices
    ports:
      - "5001:8080"
  service2:
    image: service2
    build:
      context: .
      dockerfile: Service2/Dockerfile
    networks:
      - microservices
    depends_on:
      - service1
    environment:
      - Service1Url=http://service1:8080
    ports:
      - "5002:8080"

  frontend:
    image: frontend
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    networks:
      - microservices
    ports:
      - "5000:8080"
    depends_on:
      - service2
    environment:
      - Service2Url=http://service2:8080

networks:
  microservices:
    driver: bridge